// Translated from 1003.check-if-word-is-valid-after-substitutions.py.
// Original Python source and explanation are preserved below as comments.
// #
// # @lc app=leetcode id=1003 lang=python3
// #
// # [1003] Check If Word Is Valid After Substitutions
// #
// 
// # --- Interview notes (grammar / inverse insertions, stack simulation, complexity, edges, alternatives) ---
// #
// # Problem
// # Start from empty string `t = ""`. Repeatedly choose a split `t = left + right` and replace `t` with `left + "abc" + right`
// # (insert literal `"abc"` at any position). Given final string `s`, decide whether it can be produced by zero or more such
// # insertions.
// #
// # Equivalent inverse viewpoint (canonical for coding)
// # Inserting `"abc"` is reversible by **deleting** a contiguous substring `"abc"` **provided** that deletion corresponds to
// # undoing one insertion step. Any valid `s` reduces to `""` by repeatedly deleting some `"abc"` pieces until nothing remains.
// # The stack algorithm below processes `s` left-to-right and removes `"abc"` whenever the **current built string’s suffix**
// # becomes `"abc"` — this matches the unique reverse path for strings generated by this grammar (same spirit as checking
// # balanced parentheses / reducing a context-free pattern).
// #
// # Why a stack
// # Scanning left to right, we maintain the **current irreducible prefix** of what we have read — characters that have not yet
// # been matched into completed `"abc"` blocks. Appending is push; whenever the top three symbols are `"abc"`, they cancel as
// # the reverse of one insertion. After one cancellation, the new top may again be `"abc"` (nested / adjacent reductions), so a
// # **while** loop pops until the suffix is no longer `"abc"`.
// #
// # Necessary cheap filter
// # Each insertion adds **3** characters ⇒ valid `|s|` must be divisible by **3**. Otherwise return `False` immediately.
// #
// # Algorithm
// # 1. If `len(s) % 3 != 0`, return `False`.
// # 2. Stack `st`: for each character `ch`, push; while last three are `"abc"`, pop three.
// # 3. Valid iff stack is empty at end.
// #
// # Time complexity **O(n)** — each character pushed once and popped at most once.
// #
// # Space complexity **O(n)** — stack holds at most `n` characters (typical worst case when few cancellations occur).
// #
// # Edge cases
// # • `s == "abc"` — one push triple then empty stack → `True`.
// # • Length not multiple of 3 — `False` without full scan (except empty `s` if allowed: length 0 → `True`).
// #
// # Tests (statement)
// # • `"aabcbc"` → `True`.
// # • `"abcabcababcc"` → `True`.
// # • `"abccba"` → `False`.
// #
// # Alternatives / improvements
// # • **Recursion** simulating inverse insertions — exponential without memo; stack is linear.
// # • **Explicit CFG parser** for `S → ε | S "abc" S` style grammar — stack is the pragmatic realization.
// # • Compare three stack tops without building `"abc"` string: check `st[-3]=='a'`, etc., avoids tiny string joins per step.
// #
// # --- end notes ---
// 
// # @lc code=start
// class Solution:
//     def isValid(self, s: str) -> bool:
//         if len(s) % 3:
//             return False
//         st = []
//         for ch in s:
//             st.append(ch)
//             while len(st) >= 3 and st[-3] == "a" and st[-2] == "b" and st[-1] == "c":
//                 st.pop()
//                 st.pop()
//                 st.pop()
//         return len(st) == 0
// 
// 
// # @lc code=end

#include <algorithm>
#include <array>
#include <cctype>
#include <climits>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <deque>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <queue>
#include <random>
#include <set>
#include <sstream>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
using namespace std;

// C++ translation notes:
// - Python list/deque/heap/dict/set are translated to vector/deque/priority_queue/map or unordered_map/set.
// - TreeNode and ListNode are supplied by LeetCode. Define LOCAL_LEETCODE_STUBS for local-only compilation of tree/list solutions.
#ifdef LOCAL_LEETCODE_STUBS
struct ListNode {
    int val;
    ListNode* next;
    ListNode() : val(0), next(nullptr) {}
    ListNode(int x) : val(x), next(nullptr) {}
    ListNode(int x, ListNode* next) : val(x), next(next) {}
};
struct TreeNode {
    int val;
    TreeNode* left;
    TreeNode* right;
    TreeNode() : val(0), left(nullptr), right(nullptr) {}
    TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
    TreeNode(int x, TreeNode* left, TreeNode* right) : val(x), left(left), right(right) {}
};
#endif

class Solution {
public:
    bool isValid(string s) {
        if (s.size() % 3) return false;
        vector<char> st;
        for (char ch : s) {
            st.push_back(ch);
            while (st.size() >= 3 && st[st.size() - 3] == 'a' && st[st.size() - 2] == 'b' && st.back() == 'c') {
                st.pop_back();
                st.pop_back();
                st.pop_back();
            }
        }
        return st.empty();
    }
};
