#
# @lc app=leetcode id=389 lang=python3
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (60.58%)
# Likes:    5550
# Dislikes: 520
# Total Accepted:    1.2M
# Total Submissions: 1.9M
# Testcase Example:  "\"abcd\""
#
# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
#
# Return the letter that was added to t.
#
# Example 1:
#
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
#
# Example 2:
#
# Input: s = "", t = "y"
# Output: "y"
#
# Constraints:
#
# 0 <= s.length <= 1000
#
# t.length == s.length + 1
#
# s and t consist of lowercase English letters.
#

# @lc code=start
from collections import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        """
        Interview explanation:
        t is s plus one extra character. XOR all chars of s and t — duplicates
        cancel, leaving the extra char (same as single-number XOR trick).

        Algorithm:
        - x = 0; for ch in s+t: x ^= ord(ch); return chr(x).

        Complexity: O(n) time, O(1) space.
        """
        x = 0
        for ch in s:
            x ^= ord(ch)
        for ch in t:
            x ^= ord(ch)
        return chr(x)

    def findTheDifferenceCounter(self, s: str, t: str) -> str:
        """
        Interview explanation:
        Alternate: Counter(t) - Counter(s) leaves the extra character.

        Complexity: O(n) time, O(1) alphabet space.
        """
        diff = Counter(t) - Counter(s)
        return next(iter(diff))
# @lc code=end
