#
# @lc app=leetcode id=3270 lang=python3
#
# [3270] Find the Key of the Numbers
#
# https://leetcode.com/problems/find-the-key-of-the-numbers/description/
#
# algorithms
# Easy (76.71%)
# Likes:    114
# Dislikes: 16
# Total Accepted:    55.3K
# Total Submissions: 72.1K
# Testcase Example:  "1\n10\n1000"
#
#
# You are given three positive integers num1, num2, and num3.
#
# The key of num1, num2, and num3 is defined as a four-digit number such
# that:
#
# Initially, if any number has less than four digits, it is padded with
# leading zeros.
#
# The i^th digit (1 <= i <= 4) of the key is generated by taking the
# smallest digit among the i^th digits of num1, num2, and num3.
#
# Return the key of the three numbers without leading zeros (if any).
#
# Example 1:
#
# Input: num1 = 1, num2 = 10, num3 = 1000
#
# Output: 0
#
# Explanation:
#
# On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains
# "1000".
#
# The 1^st digit of the key is min(0, 0, 1).
#
# The 2^nd digit of the key is min(0, 0, 0).
#
# The 3^rd digit of the key is min(0, 1, 0).
#
# The 4^th digit of the key is min(1, 0, 0).
#
# Hence, the key is "0000", i.e. 0.
#
# Example 2:
#
# Input: num1 = 987, num2 = 879, num3 = 798
#
# Output: 777
#
# Example 3:
#
# Input: num1 = 1, num2 = 2, num3 = 3
#
# Output: 1
#
# Constraints:
#
# 1 <= num1, num2, num3 <= 9999
#

# @lc code=start

class Solution:
    def generateKey(self, num1: int, num2: int, num3: int) -> int:
        """
        Interview explanation:
        Pad each number to 4 digits; the key's i-th digit is the min of the three
        i-th digits. Drop leading zeros in the integer result.

        Algorithm:
        - For place in 1000,100,10,1: digit = min of the three place digits; accumulate.

        Complexity: O(1) time, O(1) space.
        """
        a = f'{num1:04d}'
        b = f'{num2:04d}'
        c = f'{num3:04d}'
        key = ''.join(min(x, y, z) for x, y, z in zip(a, b, c))
        return int(key)

    def generateKey_math(self, num1: int, num2: int, num3: int) -> int:
        """
        Interview explanation:
        Alternate without strings: peel digits with mod/div.

        Algorithm:
        - For each of 4 places from least significant: take min of %10; build via place values.

        Complexity: O(1) time, O(1) space.
        """
        ans = 0
        place = 1
        for _ in range(4):
            d = min(num1 % 10, num2 % 10, num3 % 10)
            ans += d * place
            place *= 10
            num1 //= 10
            num2 //= 10
            num3 //= 10
        return ans
# @lc code=end
