#
# @lc app=leetcode id=3474 lang=python3
#
# [3474] Lexicographically Smallest Generated String
#
# https://leetcode.com/problems/lexicographically-smallest-generated-string/description/
#
# algorithms
# Hard (53.58%)
# Likes:    273
# Dislikes: 40
# Total Accepted:    65.3K
# Total Submissions: 122K
# Testcase Example:  "\"TFTF\"\n\"ab\""
#
#
# You are given two strings, str1 and str2, of lengths n and m,
# respectively.
#
# A string word of length n + m - 1 is defined to be generated by str1 and
# str2 if it satisfies the following conditions for each index 0 <= i <= n
# - 1:
#
# If str1[i] == 'T', the substring of word with size m starting at index i
# is equal to str2, i.e., word[i..(i + m - 1)] == str2.
#
# If str1[i] == 'F', the substring of word with size m starting at index i
# is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
#
# Return the lexicographically smallest possible string that can be
# generated by str1 and str2. If no string can be generated, return an
# empty string "".
#
# Example 1:
#
# Input: str1 = "TFTF", str2 = "ab"
#
# Output: "ababa"
#
# Explanation:
#
# The table below represents the string "ababa"
#
#                         Index
#                         T/F
#                         Substring of length m
#
#                         0
#                         'T'
#                         "ab"
#
#                         1
#                         'F'
#                         "ba"
#
#                         2
#                         'T'
#                         "ab"
#
#                         3
#                         'F'
#                         "ba"
#
# The strings "ababa" and "ababb" can be generated by str1 and str2.
#
# Return "ababa" since it is the lexicographically smaller string.
#
# Example 2:
#
# Input: str1 = "TFTF", str2 = "abc"
#
# Output: ""
#
# Explanation:
#
# No string that satisfies the conditions can be generated.
#
# Example 3:
#
# Input: str1 = "F", str2 = "d"
#
# Output: "a"
#
# Constraints:
#
# 1 <= n == str1.length <= 10^4
#
# 1 <= m == str2.length <= 500
#
# str1 consists only of 'T' or 'F'.
#
# str2 consists only of lowercase English characters.
#

# @lc code=start
class Solution:
    def generateString(self, str1: str, str2: str) -> str:
        """
        Interview explanation:
        Build the shortest lex string of length n+m-1 satisfying T/F window
        constraints against str2.

        Algorithm:
        - Initialize answer with 'a's; apply all 'T' windows (fix positions).
        - For each 'F' window that still equals str2, change the rightmost
          unfixed char to 'b'. Impossible if the window is fully fixed.

        Complexity: O(n m) time, O(n + m) space.
        """
        n, m = len(str1), len(str2)
        ans = ["a"] * (n + m - 1)
        fixed = [False] * (n + m - 1)

        for i, bit in enumerate(str1):
            if bit != "T":
                continue
            for j, ch in enumerate(str2):
                pos = i + j
                if fixed[pos] and ans[pos] != ch:
                    return ""
                ans[pos] = ch
                fixed[pos] = True

        for i, bit in enumerate(str1):
            if bit != "F":
                continue
            if "".join(ans[i : i + m]) != str2:
                continue
            for j in range(i + m - 1, i - 1, -1):
                if not fixed[j]:
                    ans[j] = "b"
                    break
            else:
                return ""

        return "".join(ans)
# @lc code=end

