#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <condition_variable>
#include <cstdlib>
#include <deque>
#include <functional>
#include <map>
#include <mutex>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
using namespace std;

class Solution {
public:
    vector<string> mostVisitedPattern(vector<string>& username, vector<int>& timestamp, vector<string>& website) {
        int n = username.size();
        vector<int> order(n);
        iota(order.begin(), order.end(), 0);
        sort(order.begin(), order.end(), [&](int a, int b) {
            return timestamp[a] < timestamp[b];
        });

        unordered_map<string, vector<string>> visits;
        for (int id : order) visits[username[id]].push_back(website[id]);

        map<array<string, 3>, int> count;
        for (auto& [user, sites] : visits) {
            set<array<string, 3>> seen;
            int m = sites.size();
            for (int i = 0; i < m; ++i) {
                for (int j = i + 1; j < m; ++j) {
                    for (int k = j + 1; k < m; ++k) {
                        seen.insert({sites[i], sites[j], sites[k]});
                    }
                }
            }
            for (const auto& pattern : seen) ++count[pattern];
        }

        array<string, 3> best;
        int bestCount = -1;
        for (const auto& [pattern, freq] : count) {
            if (freq > bestCount) {
                bestCount = freq;
                best = pattern;
            }
        }

        return {best[0], best[1], best[2]};
    }
};

/*
Interview Explanation

Core idea:
The score of a 3-sequence is the number of users who visited that sequence in
order. A user should count at most once per pattern, even if they produce it
multiple times.

C++ data structures:
- Sorted index vector orders events by timestamp.
- unordered_map<string, vector<string>> groups each user's chronological sites.
- set<array<string,3>> deduplicates patterns per user.
- map<array<string,3>, int> stores global counts in lexicographic order.

Algorithm:
1. Sort all events by timestamp.
2. Build each user's ordered website list.
3. Generate all i<j<k triples per user and deduplicate them.
4. Increment global count once per user-pattern.
5. Pick the highest count; map iteration naturally resolves lexicographic ties.

Correctness:
Every valid 3-sequence for a user is generated by some i<j<k triple. The per
user set ensures the user contributes at most one vote to a pattern. Global
counts therefore equal problem scores, and choosing max count with lexicographic
map order gives the required answer.

Complexity:
If a user has v visits, triple generation is O(v^3). Total constraints are
small enough. Space is O(number of generated patterns).

Edge cases:
- Repeated websites are valid sequence elements.
- Ties choose lexicographically smallest pattern.
*/
