#
# @lc app=leetcode id=1332 lang=python3
#
# [1332] Remove Palindromic Subsequences
#
# https://leetcode.com/problems/remove-palindromic-subsequences/description/
#
# algorithms
# Easy (77.18%)
# Likes:    1756
# Dislikes: 1805
# Total Accepted:    157K
# Total Submissions: 203K
# Testcase Example:  "\"ababa\""
#
# You are given a string s consisting only of letters 'a' and 'b'. In a single
# step you can remove one palindromic subsequence from s.
#
# Return the minimum number of steps to make the given string empty.
#
# A string is a subsequence of a given string if it is generated by deleting
# some characters of a given string without changing its order. Note that a
# subsequence does not necessarily need to be contiguous.
#
# A string is called palindrome if is one that reads the same backward as well
# as forward.
#
# Example 1:
#
# Input: s = "ababa"
# Output: 1
# Explanation: s is already a palindrome, so its entirety can be removed in a
# single step.
#
# Example 2:
#
# Input: s = "abb"
# Output: 2
# Explanation: "abb" -> "bb" -> "".
# Remove palindromic subsequence "a" then "bb".
#
# Example 3:
#
# Input: s = "baabb"
# Output: 2
# Explanation: "baabb" -> "b" -> "".
# Remove palindromic subsequence "baab" then "b".
#
# Constraints:
#
# 1 <= s.length <= 1000
#
# s[i] is either 'a' or 'b'.
#

# @lc code=start
class Solution:
    def removePalindromeSub(self, s: str) -> int:
        """
        Interview explanation:
        Subsequence (not substring), alphabet {a,b}. Any string of one letter
        is a palindrome. If s is palindrome remove in 1 step; else remove all
        a's then all b's (2 steps). Empty -> 0.

        Algorithm:
        - If not s: 0; if s==s[::-1]: 1; else 2.

        Complexity: O(n) time, O(n) space (or O(1) two pointers).
        """
        if not s:
            return 0
        return 1 if s == s[::-1] else 2
# @lc code=end

